/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Student */

#ifndef _Included_Student
#define _Included_Student
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Student
 * Method:    printInfo
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_test22_TestMethodLocal_000241Student_printInfo
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
