/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test19_TestGenericClass */

#ifndef _Included_test19_TestGenericClass
#define _Included_test19_TestGenericClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test19_TestGenericClass
 * Method:    callPrintMembers
 * Signature: (Ltest19/Group;)V
 */
JNIEXPORT void JNICALL Java_test19_TestGenericClass_callPrintMembers
  (JNIEnv *, jclass, jobject);

/*
 * Class:     test19_TestGenericClass
 * Method:    callPrintMembersParameterized
 * Signature: (Ltest19/Group;)V
 */
JNIEXPORT void JNICALL Java_test19_TestGenericClass_callPrintMembersParameterized
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
