/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test15_TestConstructorCall */

#ifndef _Included_test15_TestConstructorCall
#define _Included_test15_TestConstructorCall
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test15_TestConstructorCall
 * Method:    createPerson
 * Signature: (Ljava/lang/String;I)Ltest15/Person;
 */
JNIEXPORT jobject JNICALL Java_test15_TestConstructorCall_createPerson
  (JNIEnv *, jclass, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
