/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test22_Person_Book */

#ifndef _Included_test22_Person_Book
#define _Included_test22_Person_Book
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test22_Person_Book
 * Method:    printTitle
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_test22_Person_00024Book_printTitle
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
