/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test7_TestAccessFields */

#ifndef _Included_test7_TestAccessFields
#define _Included_test7_TestAccessFields
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test7_TestAccessFields
 * Method:    printName
 * Signature: (Ltest7/Person;)V
 */
JNIEXPORT void JNICALL Java_test7_TestAccessFields_printName
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
