/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test16_AiryFunction */

#ifndef _Included_test16_AiryFunction
#define _Included_test16_AiryFunction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test16_AiryFunction
 * Method:    bi
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_test16_AiryFunction_bi
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     test16_AiryFunction
 * Method:    ai
 * Signature: (Ljava/util/List;)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_test16_AiryFunction_ai
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
