/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test8_TestStaticFields */

#ifndef _Included_test8_TestStaticFields
#define _Included_test8_TestStaticFields
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test8_TestStaticFields
 * Method:    printPersonInfo
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_test8_TestStaticFields_printPersonInfo
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
