/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test_TestOverrideSuperClass */

#ifndef _Included_test_TestOverrideSuperClass
#define _Included_test_TestOverrideSuperClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test_TestOverrideSuperClass
 * Method:    func
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_test_TestOverrideSuperClass_func
  (JNIEnv *, jobject, jdouble);

#ifdef __cplusplus
}
#endif
#endif
