/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test2_Overload1 */

#ifndef _Included_test2_Overload1
#define _Included_test2_Overload1
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test2_Overload1
 * Method:    func
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_test2_Overload1_func__D
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     test2_Overload1
 * Method:    func
 * Signature: ([D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_test2_Overload1_func___3D
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     test2_Overload1
 * Method:    func
 * Signature: ([DLjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_test2_Overload1_func___3DLjava_lang_String_2
  (JNIEnv *, jobject, jdoubleArray, jstring);

/*
 * Class:     test2_Overload1
 * Method:    func
 * Signature: (Ltest2/Overload1;Ltest2/Overload1;)V
 */
JNIEXPORT void JNICALL Java_test2_Overload1_func__Ltest2_Overload1_2Ltest2_Overload1_2
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
