/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test11_TestGlobalCaching */

#ifndef _Included_test11_TestGlobalCaching
#define _Included_test11_TestGlobalCaching
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test11_TestGlobalCaching
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_test11_TestGlobalCaching_initIDs
  (JNIEnv *, jclass);

/*
 * Class:     test11_TestGlobalCaching
 * Method:    setProperties
 * Signature: (Ltest11/Person;Ljava/lang/String;Ljava/lang/String;ID)V
 */
JNIEXPORT void JNICALL Java_test11_TestGlobalCaching_setProperties
  (JNIEnv *, jclass, jobject, jstring, jstring, jint, jdouble);

/*
 * Class:     test11_TestGlobalCaching
 * Method:    setFirstName
 * Signature: (Ltest11/Person;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_test11_TestGlobalCaching_setFirstName
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     test11_TestGlobalCaching
 * Method:    setLastName
 * Signature: (Ltest11/Person;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_test11_TestGlobalCaching_setLastName
  (JNIEnv *, jclass, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
