/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test23_FileReader */

#ifndef _Included_test23_FileReader
#define _Included_test23_FileReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test23_FileReader
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_test23_FileReader_initIDs
  (JNIEnv *, jclass);

/*
 * Class:     test23_FileReader
 * Method:    open0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_test23_FileReader_open0
  (JNIEnv *, jobject);

/*
 * Class:     test23_FileReader
 * Method:    close0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_test23_FileReader_close0
  (JNIEnv *, jobject);

/*
 * Class:     test23_FileReader
 * Method:    next0
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_test23_FileReader_next0
  (JNIEnv *, jobject);

/*
 * Class:     test23_FileReader
 * Method:    eof
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_test23_FileReader_eof
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
