/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test5_TestObjectArray */

#ifndef _Included_test5_TestObjectArray
#define _Included_test5_TestObjectArray
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test5_TestObjectArray
 * Method:    ones
 * Signature: (II)[[D
 */
JNIEXPORT jobjectArray JNICALL Java_test5_TestObjectArray_ones
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     test5_TestObjectArray
 * Method:    max0
 * Signature: ([D)D
 */
JNIEXPORT jdouble JNICALL Java_test5_TestObjectArray_max0
  (JNIEnv *, jobject, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
