/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test23_FileReader2 */

#ifndef _Included_test23_FileReader2
#define _Included_test23_FileReader2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test23_FileReader2
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_test23_FileReader2_initIDs
  (JNIEnv *, jclass);

/*
 * Class:     test23_FileReader2
 * Method:    open0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_test23_FileReader2_open0
  (JNIEnv *, jobject);

/*
 * Class:     test23_FileReader2
 * Method:    close0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_test23_FileReader2_close0
  (JNIEnv *, jobject);

/*
 * Class:     test23_FileReader2
 * Method:    next0
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_test23_FileReader2_next0
  (JNIEnv *, jobject);

/*
 * Class:     test23_FileReader2
 * Method:    eof
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_test23_FileReader2_eof
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
