/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test19_TestGenericsMethod */

#ifndef _Included_test19_TestGenericsMethod
#define _Included_test19_TestGenericsMethod
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test19_TestGenericsMethod
 * Method:    printInfoNative
 * Signature: (Ljava/lang/Number;)V
 */
JNIEXPORT void JNICALL Java_test19_TestGenericsMethod_printInfoNative
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
