/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test2_Overload */

#ifndef _Included_test2_Overload
#define _Included_test2_Overload
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test2_Overload
 * Method:    func
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_test2_Overload_func__D
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     test2_Overload
 * Method:    func
 * Signature: (Ltest2/My_Class;)D
 */
JNIEXPORT jdouble JNICALL Java_test2_Overload_func__Ltest2_My_1Class_2
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
