/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test14_TestInterfaceCall */

#ifndef _Included_test14_TestInterfaceCall
#define _Included_test14_TestInterfaceCall
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test14_TestInterfaceCall
 * Method:    callValue
 * Signature: (Ltest14/MathFunction;D)D
 */
JNIEXPORT jdouble JNICALL Java_test14_TestInterfaceCall_callValue
  (JNIEnv *, jclass, jobject, jdouble);

/*
 * Class:     test14_TestInterfaceCall
 * Method:    callValueScaled
 * Signature: (Ltest14/MathFunction;D)D
 */
JNIEXPORT jdouble JNICALL Java_test14_TestInterfaceCall_callValueScaled
  (JNIEnv *, jclass, jobject, jdouble);

/*
 * Class:     test14_TestInterfaceCall
 * Method:    callFunctionScaled
 * Signature: (Ltest14/MathFunction;)Ltest14/MathFunction;
 */
JNIEXPORT jobject JNICALL Java_test14_TestInterfaceCall_callFunctionScaled
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
