/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test22_Person_Bag */

#ifndef _Included_test22_Person_Bag
#define _Included_test22_Person_Bag
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test22_Person_Bag
 * Method:    printSize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_test22_Person_00024Bag_printSize__
  (JNIEnv *, jobject);

/*
 * Class:     test22_Person_Bag
 * Method:    printSize
 * Signature: (Ltest22/Person$Bag;)V
 */
JNIEXPORT void JNICALL Java_test22_Person_00024Bag_printSize__Ltest22_Person_00024Bag_2
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
