/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test10_TestMethodCatching */

#ifndef _Included_test10_TestMethodCatching
#define _Included_test10_TestMethodCatching
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test10_TestMethodCatching
 * Method:    setAge
 * Signature: (Ltest10/Person;I)V
 */
JNIEXPORT void JNICALL Java_test10_TestMethodCatching_setAge
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     test10_TestMethodCatching
 * Method:    setName
 * Signature: (Ltest10/Person;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_test10_TestMethodCatching_setName
  (JNIEnv *, jclass, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
