/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test_TestOverrideSubClass */

#ifndef _Included_test_TestOverrideSubClass
#define _Included_test_TestOverrideSubClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test_TestOverrideSubClass
 * Method:    func
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_test_TestOverrideSubClass_func
  (JNIEnv *, jobject, jdouble);

#ifdef __cplusplus
}
#endif
#endif
