/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test22_TestInnerClass */

#ifndef _Included_test22_TestInnerClass
#define _Included_test22_TestInnerClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test22_TestInnerClass
 * Method:    createBag
 * Signature: ()Ltest22/Person/Bag;
 */
JNIEXPORT jobject JNICALL Java_test22_TestInnerClass_createBag
  (JNIEnv *, jclass);

/*
 * Class:     test22_TestInnerClass
 * Method:    createBook
 * Signature: (Ltest22/Person;)Ltest22/Person/Book;
 */
JNIEXPORT jobject JNICALL Java_test22_TestInnerClass_createBook
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
