/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test4_TestPrimitive */

#ifndef _Included_test4_TestPrimitive
#define _Included_test4_TestPrimitive
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test4_TestPrimitive
 * Method:    isOdd
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_test4_TestPrimitive_isOdd
  (JNIEnv *, jobject, jint);

/*
 * Class:     test4_TestPrimitive
 * Method:    func1
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_test4_TestPrimitive_func1
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     test4_TestPrimitive
 * Method:    func2
 * Signature: (B)F
 */
JNIEXPORT jfloat JNICALL Java_test4_TestPrimitive_func2
  (JNIEnv *, jobject, jbyte);

#ifdef __cplusplus
}
#endif
#endif
