/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test20_TestJNIReflection */

#ifndef _Included_test20_TestJNIReflection
#define _Included_test20_TestJNIReflection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test20_TestJNIReflection
 * Method:    callNameField
 * Signature: (Ltest20/Person;Ljava/lang/reflect/Field;)V
 */
JNIEXPORT void JNICALL Java_test20_TestJNIReflection_callNameField
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     test20_TestJNIReflection
 * Method:    callMethod
 * Signature: (Ltest20/Person;Ljava/lang/reflect/Method;)V
 */
JNIEXPORT void JNICALL Java_test20_TestJNIReflection_callMethod
  (JNIEnv *, jclass, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
