/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test2_Overload2 */

#ifndef _Included_test2_Overload2
#define _Included_test2_Overload2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test2_Overload2
 * Method:    func
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_test2_Overload2_func__D
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     test2_Overload2
 * Method:    func
 * Signature: ([D)D
 */
JNIEXPORT jdouble JNICALL Java_test2_Overload2_func___3D
  (JNIEnv *, jclass, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
