/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test12_TestMethodCall */

#ifndef _Included_test12_TestMethodCall
#define _Included_test12_TestMethodCall
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test12_TestMethodCall
 * Method:    printPersonName
 * Signature: (Ltest12/Person;)V
 */
JNIEXPORT void JNICALL Java_test12_TestMethodCall_printPersonName
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
