/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test4_TestTypes */

#ifndef _Included_test4_TestTypes
#define _Included_test4_TestTypes
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test4_TestTypes
 * Method:    func1
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_test4_TestTypes_func1__Z
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     test4_TestTypes
 * Method:    func1
 * Signature: (ZD)Z
 */
JNIEXPORT jboolean JNICALL Java_test4_TestTypes_func1__ZD
  (JNIEnv *, jobject, jboolean, jdouble);

/*
 * Class:     test4_TestTypes
 * Method:    func2
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_test4_TestTypes_func2__
  (JNIEnv *, jobject);

/*
 * Class:     test4_TestTypes
 * Method:    func2
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_test4_TestTypes_func2__S
  (JNIEnv *, jobject, jshort);

/*
 * Class:     test4_TestTypes
 * Method:    func3
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_test4_TestTypes_func3__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     test4_TestTypes
 * Method:    func3
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_test4_TestTypes_func3__JD
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     test4_TestTypes
 * Method:    func4
 * Signature: (CLjava/lang/Double;)V
 */
JNIEXPORT void JNICALL Java_test4_TestTypes_func4__CLjava_lang_Double_2
  (JNIEnv *, jobject, jchar, jobject);

/*
 * Class:     test4_TestTypes
 * Method:    func4
 * Signature: (Ljava/lang/Double;)V
 */
JNIEXPORT void JNICALL Java_test4_TestTypes_func4__Ljava_lang_Double_2
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
