/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test21_ConstantsClass */

#ifndef _Included_test21_ConstantsClass
#define _Included_test21_ConstantsClass
#ifdef __cplusplus
extern "C" {
#endif
#undef test21_ConstantsClass_BYTE_VALUE
#define test21_ConstantsClass_BYTE_VALUE 1L
#undef test21_ConstantsClass_SHORT_VALUE
#define test21_ConstantsClass_SHORT_VALUE 2L
#undef test21_ConstantsClass_INT_VALUE
#define test21_ConstantsClass_INT_VALUE 3L
#undef test21_ConstantsClass_LONG_VALUE
#define test21_ConstantsClass_LONG_VALUE 4LL
#undef test21_ConstantsClass_FLOAT_VALUE
#define test21_ConstantsClass_FLOAT_VALUE 2.1f
#undef test21_ConstantsClass_DOUBLE_VALUE
#define test21_ConstantsClass_DOUBLE_VALUE -10.5
#undef test21_ConstantsClass_TRUE_VALUE
#define test21_ConstantsClass_TRUE_VALUE 1L
#undef test21_ConstantsClass_FALSE_VALUE
#define test21_ConstantsClass_FALSE_VALUE 0L
/*
 * Class:     test21_ConstantsClass
 * Method:    printValues
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_test21_ConstantsClass_printValues
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
