/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test17_TestInheritance */

#ifndef _Included_test17_TestInheritance
#define _Included_test17_TestInheritance
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test17_TestInheritance
 * Method:    callSpeak
 * Signature: (Ltest17/Animal;)V
 */
JNIEXPORT void JNICALL Java_test17_TestInheritance_callSpeak
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
