/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test5_TestPrimitiveArrays */

#ifndef _Included_test5_TestPrimitiveArrays
#define _Included_test5_TestPrimitiveArrays
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test5_TestPrimitiveArrays
 * Method:    linspace
 * Signature: (DDI)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_test5_TestPrimitiveArrays_linspace
  (JNIEnv *, jobject, jdouble, jdouble, jint);

/*
 * Class:     test5_TestPrimitiveArrays
 * Method:    func1
 * Signature: ([D)D
 */
JNIEXPORT jdouble JNICALL Java_test5_TestPrimitiveArrays_func1
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     test5_TestPrimitiveArrays
 * Method:    func2
 * Signature: ([D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_test5_TestPrimitiveArrays_func2
  (JNIEnv *, jobject, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
