/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test9_TestSetFields */

#ifndef _Included_test9_TestSetFields
#define _Included_test9_TestSetFields
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test9_TestSetFields
 * Method:    setNameAndAge
 * Signature: (Ltest9/Person;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_test9_TestSetFields_setNameAndAge
  (JNIEnv *, jobject, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
